const ACTION_CONSTANTS = {
    // user
    USER_DETAILS: "USERDETAILS",
    USER_SIGNUP_STATUS: "USER_SIGNUP_STATUS",
    USER_LOGOUT:"USER_LOGOUT",
    USER_PHONE_NUMBER_VERIFY:'USER_PHONE_NUMBER_VERIFY',
    USER_PHONE_NUMBER:'USER_PHONE_NUMBER',

    // cricket
    LIVE_MATCH_DETAILS:'LIVE_MATCH_DETAILS',
    FIXTURE_MATCH_DETAILS:'FIXTURE_MATCH_DETAILS',
    FINISHED_MATCH_DETAILS:'FINISHED_MATCH_DETAILS',
    UPCOMING_MATCH_DETAILS:'UPCOMING_MATCH_DETAILS',
    TEAM_RANKINGS:'TEAM_RANKINGS',
    // user profile
    USER_PROFILE:'USER_PROFILE',
    USER_PROFILE_PICTURE:'USER_PROFILE_PICTURE',

    SET_CURRENT_MATCH_ID: 'SET_CURRENT_MATCH_ID',
    GET_LEAGUES:'GET_LEAGUES',

    // favourites
    GET_FAVOURITES:'GET_FAVOURITES',
    PLAYERS:'PLAYERS',
    LEAGUES:'LEAGUES',
    TEAMS:'TEAMS',
    GET_SEARCH_RESULTS:'SEARCHED_PLAYERS',
    SET_CURRENT_MATCH_DATA: 'SET_CURRENT_MATCH_DATA',

    //admin
    ADMIN_MESSAGE:'ADMIN_MESSAGE',
    CLEAR_ADMIN_MESSAGE:'CLEAR_ADMIN_MESSAGE',
    ADMIN_UPCOMING_MATCHES:"ADMIN_UPCOMING_MATCHES",
    //news
    GET_NEWS_LIST:'GET_NEWS_LIST',
    GET_NEWS_DETAILS:'GET_NEWS_DETAILS'
};

export default ACTION_CONSTANTS;