import { SERVER_BASE_URL } from "./config";
export const API = {
    USER_REGISTER: `${SERVER_BASE_URL}/api/user/auth/register`,
    USER_LOGIN: `${SERVER_BASE_URL}/api/user/auth/login`,
    USER_LOGOUT: `${SERVER_BASE_URL}/api/user/auth/logout`,
    VERIFY_PHONE_NUMBER: `${SERVER_BASE_URL}/api/user/auth/verifyPhoneNumber`,
    OTP_LOGIN: `${SERVER_BASE_URL}/api/user/auth/otpLogin`,
    // GET_LIVE_MATCHES: `${SERVER_BASE_URL}/api/cricket/get-live-matches`,
    GET_FINISHED_MATCHES: `${SERVER_BASE_URL}/api/cricket/get-finished-matches`,
    GET_UPCOMING_MATCHES: `${SERVER_BASE_URL}/api/cricket/get-upcoming-matches`,
    GET_LEAGUES: `${SERVER_BASE_URL}/api/cricket/get-leagues`,
    GET_USER_DETAILS: `${SERVER_BASE_URL}/api/user/profile/user-details`,
    EDIT_USER_PROFILE: `${SERVER_BASE_URL}/api/user/profile/edit-user-details`,
    EDIT_USER_PASSWORD: `${SERVER_BASE_URL}/api/user/profile/edit-user-password`,
    UPLOAD_USER_PROFILE_PICTURE: `${SERVER_BASE_URL}/api/user/profile/upload-profile-picture`,
    GET_USER_PROFILE_PICTURE: `${SERVER_BASE_URL}/api/user/profile/fetch-profile-picture`,
    GET_TEAM_RANKING: `${SERVER_BASE_URL}/api/cricket/get-team-rankings`,
    GET_ALL_FAVOURITES: `${SERVER_BASE_URL}/api/favourites/get-all-favourites`,
    GET_PLAYERS: `${SERVER_BASE_URL}/api/favourites/players`,
    GET_TEAMS: `${SERVER_BASE_URL}/api/favourites/teams`,
    GET_FAV_LEAGUES: `${SERVER_BASE_URL}/api/favourites/leagues`,
    ADD_TEAMS_TO_FAVOURITE: `${SERVER_BASE_URL}/api/favourites/add-favourite-teams`,
    ADD_LEAGUES_TO_FAVOURITE: `${SERVER_BASE_URL}/api/favourites/add-favourite-leagues`,
    ADD_PLAYERS_TO_FAVOURITE: `${SERVER_BASE_URL}/api/favourites/add-favourite-players`,
    SEARCH_FOR_PLAYERS: `${SERVER_BASE_URL}/api/favourites/get-players-search-result`,
    DELETE_FAVOURITE_PLAYERS: `${SERVER_BASE_URL}/api/favourites/delete-favourite-players`,
    DELETE_FAVOURITE_TEAMS: `${SERVER_BASE_URL}/api/favourites/delete-favourite-teams`,
    DELETE_FAVOURITE_LEAGUES: `${SERVER_BASE_URL}/api/favourites/delete-favourite-leagues`,
    ADMIN_AUTHENTICATION: `${SERVER_BASE_URL}/admin/authentication`,
    PLAYER_IMAGE_UPLOAD: `${SERVER_BASE_URL}/admin/upload-player-image`,
    GET_PLAYER_IMAGE: (playerId) => `${SERVER_BASE_URL}/admin/get-player-image/${playerId}`,
    GET_USER_PROFILE: (userId) => `${SERVER_BASE_URL}/admin/get-user-profile/${userId}`,
    GET_NEWS_LIST:"https://cricbuzz-cricket.p.rapidapi.com/news/v1/index",
    GET_NEWS_DETAILS:(newsID)=>`https://cricbuzz-cricket.p.rapidapi.com/news/v1/detail/${newsID}`,
    GET_NEWS_IMAGES:(imageId)=> `https://cricbuzz-cricket.p.rapidapi.com/img/v1/i1/c${imageId}/i.jpg?p=thumb`,
    ADMIN_SEARCH_PLAYERS:`${SERVER_BASE_URL}/admin/get-players-searchlist`,
    ADMIN_UPCOMING_MATCHES:`${SERVER_BASE_URL}/admin/get-upcoming-matches`,
    WEB_BANNER_IMAGE_UPLOAD:`${SERVER_BASE_URL}/admin/upload-banner-image-web`,
    MOBILE_BANNER_IMAGE_UPLOAD:`${SERVER_BASE_URL}/admin/upload-banner-image-mobile`,
    GET_BANNER_IMAGE:`${SERVER_BASE_URL}/admin/get-banner-image`,
};